### ISSUE TITLE
Not working on Fedora 25

### ISSUE THREAD

**Issue by Lemmiwinks** [kotelnik/firefox-extension-unity-launcher-api-e10s#1]
I tried to get this to work in Fedora 25 on KDE Plasma 5.8.4 by following your instructions on https://addons.mozilla.org/en-US/firefox/addon/unity-launcher-api-addon-e10s but it simply does not show the progress and download count in the task bar. Any idea what I'm doing wrong?

**Comment by kotelnik** [comment]
Please try this to narrow down the problem:
1) Restart Firefox
2) Go to about:debugging page
3) Click Debug button next to the add-on
4) Then you'll need to press ok to connect to debugger -> javascript console should show up
5) Now download a file.
6) Javascript console should write messages like:
* postMessage("count=1")
* postMessage("progress=0.001")

Look for errors there - error 'File closed' is fine, ignore it. But error 'File at path "/home/username/.mozilla/native-messaging-hosts/launcher_api_firefox_stdin.py" does not exist, or is not executable' is helpful. Feel free to post the console log so I can try to analyze the problem.

Few more things to check:
* ensure launcher_api_firefox_stdin.py is executable
* ensure python3 command is available
* ensure gdbus command is available and also that LauncherAPI is really working - try this command (it should show download count 1 in your taskbar):
```
gdbus emit --session --object-path / --signal com.canonical.Unity.LauncherEntry.Update firefox "{'progress-visible': <'true'>, 'count-visible': <'true'>, 'count': <'1'>}"
```

**Comment by Lemmiwinks** [comment]
Thanks for your quick and detailed reply!
Ok I followed your instructions on debugging the addon and here are the results from the java script console: 

`postMessage("count=1")  background.js:5:5
postMessage("progress=0.001")  background.js:5:5
Error parsing native host manifest /home/andy/.mozilla/native-messaging-hosts/launcher_api_firefox_stdin.py.json: JSON.parse: unexpected character at line 5 column 1 of the JSON data NativeMessaging.jsm:111
	_tryPath/< resource://gre/modules/NativeMessaging.jsm:111:11
GET 
http://vx2-downloads.raspberrypi.org/raspbian/images/2012-08-16-wheezy-raspbian/2012-08-16-wheezy-raspbian.zip [Mixed Content]
[HTTP/1.1 200 OK]
No such native application launcher_api_firefox_stdin.py NativeMessaging.jsm:188
	this.NativeApp</this.startupPromise< resource://gre/modules/NativeMessaging.jsm:188:17
Error: No such native application launcher_api_firefox_stdin.py  NativeMessaging.jsm:188:17
Error: Attempt to postMessage on disconnected port  (unknown)
Error: No such native application launcher_api_firefox_stdin.py  NativeMessaging.jsm:188:17
`

- launcher_api_firefox_stdin.py is executable
- python3 is available
- gdbus command you posted works!

**Comment by kotelnik** [comment]
Thanks! From to log I can see the problem. There is something wrong with the manifest file (launcher_api_firefox_stdin.py.json). In your case, it should contain this:
```
{
  "name": "launcher_api_firefox_stdin.py",
  "description": "Host for native LauncherAPI firefox calls.",
  "path": "/home/andy/.mozilla/native-messaging-hosts/launcher_api_firefox_stdin.py",
  "type": "stdio",
  "allowed_extensions": [ "firefox_extension_unity_launcher_api_e10s@kotelnik" ]
}
```
What it actually contain? Please check that there isn't missing quote (") or comma or somehing.

**Comment by Lemmiwinks** [comment]
I'm sorry, I somehow mixed up files yesterday, so the json file was a complete mess. Shouldn't do that late at night...

I corrected this now, but I get the following error:

`GET 
http://vx2-downloads.raspberrypi.org/raspbian/images/2012-08-16-wheezy-raspbian/2012-08-16-wheezy-raspbian.zip [Mixed Content]
[HTTP/1.1 200 OK]
[object Object] NativeMessaging.jsm:218
	this.NativeApp</this.startupPromise< resource://gre/modules/NativeMessaging.jsm:218:9
Error: Attempt to postMessage on disconnected port (unknown)
[object Object]  NativeMessaging.jsm:218
	this.NativeApp</this.startupPromise< resource://gre/modules/NativeMessaging.jsm:218:9
Error: Attempt to postMessage on disconnected port  (unknown)
[object Object]` and so on...

**Comment by kotelnik** [comment]
I assume that you've restarted Firefox after correcting the manifest file. So now I'm out of ideas what could be wrong. Can you please pack send me contents of your ~/.mozilla/native-messaging-hosts/ folder e.g. in tar.gz archive?

**Comment by Lemmiwinks** [comment]
Yes sure I did!
[native-messaging-hosts.tar.gz](https://github.com/kotelnik/firefox-extension-unity-launcher-api-e10s/files/736887/native-messaging-hosts.tar.gz)
Here are my files! Thanks!

**Comment by kotelnik** [comment]
Thanks. The executable launcher_api_firefox_stdin.py file has wrong contents. It should contain this (sending corrected archive). 
[native-messaging-hosts_fixed.tar.gz](https://github.com/kotelnik/firefox-extension-unity-launcher-api-e10s/files/736890/native-messaging-hosts_fixed.tar.gz)

**Comment by Lemmiwinks** [comment]
Thanks a lot! Now it works! Something went really wrong here. I don't understand right now, where I got the wrong files from. Anyway, thanks a lot!

**Comment by kotelnik** [comment]
NP, I'm glad it works :).
